services:

  nginx:
    container_name: tradedealer_nginx
    image: nginx:1.29
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/log/nginx:/var/log/nginx
      - ./:/var/www/html
    depends_on:
      - php-fpm
      - mariadb
    networks:
      - app-network

  php-fpm:
    container_name: tradedealer_php-fpm
    build: ./.docker/php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    container_name: tradedealer_mariadb
    image: mariadb:11.8
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mariadb/data/db/mysql:/var/lib/mysql
      - ./.docker/mariadb/conf.d/my.conf:/etc/mysql/conf.d/my.cnf
      - ./:/var/www/html
    environment:
      - MYSQL_DATABASE=tradedealer
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge